[package]
name = "sailor_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "sailor"

[dependencies]
owo-colors = "4.0.0"
rand = "0.8.5"
sailor_core = { path = "../core" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
