[package]
name = "sail_daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "saild"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
