[package]
name = "sailor_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
pin-project = "1.1.5"
sailor_config = { path = "../config" }
sailor_core = { path = "../core" }
sailor_web = { path = "../web" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
toml = "0.8.14"
tower.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3.8"
wasm-bindgen = "0.2.92"

[[bin]]
name = "sailord"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
hydrate = ["sailor_web/hydrate"]

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "sailor"

# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"

# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/app.css
style-file = "../web/style/main.scss"
# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
#
# Optional. Env: LEPTOS_ASSETS_DIR.
assets-dir = "../web/public"

# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"
