name: deploy
on:
  push:
    branches:
      - main
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile project
        run: just build-release

      - name: List binaries
        run: ls -lah ./target/release/

      # - name: Set up SSH
      #   run: |
      #     mkdir -m 700 $HOME/.ssh
      #     echo "${{ secrets.SSH_HOST_FINGERPRINT }}" > $HOME/.ssh/known_hosts
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
      #     chmod 400 $HOME/.ssh/id_ed25519

      # - name: Copy new binaries to server
      #   run: |
      #     mkdir /tmp/sail
      #     cp install/systemd.service /tmp/sail/sail.service
      #     cp install/systemd.socket /tmp/sail/sail.socket
      #     cp target/release/sail /tmp/sail/sail
      #     cp target/release/saild /tmp/sail/saild
      #     scp -r /tmp/sail github@${{ secrets.SSH_HOST }}:/tmp/

      # - name: Update installation on server
      #   run: |
      #     ssh github@${{ secrets.SSH_HOST }} /bin/bash << EOF
      #       sudo cp /tmp/sail/sail.service /usr/lib/systemd/system/sail.service
      #       sudo cp /tmp/sail/sail.socket /usr/lib/systemd/system/sail.socket
      #       sudo systemctl daemon-reload
      #       sudo mv /tmp/sail/sail /usr/local/bin/sail
      #       sudo mv /tmp/sail/saild /usr/local/bin/saild
      #       sudo systemctl reset-failed
      #       sudo systemctl restart sail
      #       rm -rf /tmp/sail
      #     EOF
